# Generated by Django 2.2.28 on 2023-03-19 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, upload_to='blog_images')),
                ('text', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No-Name', max_length=128)),
                ('text', models.CharField(max_length=1000)),
                ('spotifyURL', models.CharField(max_length=128)),
                ('youtubeURL', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='cover_images')),
                ('genre', models.CharField(max_length=128)),
                ('madeBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicBlogger.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='profile_images')),
                ('artist', models.ManyToManyField(to='musicBlogger.Artist')),
                ('follows', models.ManyToManyField(related_name='_userprofile_follows_+', to='musicBlogger.UserProfile')),
                ('likedSong', models.ManyToManyField(related_name='liked_song', to='musicBlogger.Songs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicBlogger.Blogs')),
                ('commentedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicBlogger.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='postedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicBlogger.UserProfile'),
        ),
    ]
