# Generated by Django 2.2.28 on 2023-03-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlogger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='name',
        ),
    ]
