# Generated by Django 4.1.7 on 2023-03-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'verbose_name_plural': 'Songs'},
        ),
    ]
