# Generated by Django 4.1.7 on 2023-03-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlogger', '0002_auto_20230319_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='postedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='musicBlogger.userprofile'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='musicBlogger.blogs'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='musicBlogger.userprofile'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='madeBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='musicBlogger.artist'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='artist',
            field=models.ManyToManyField(related_name='user_profile', to='musicBlogger.artist'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='likedSong',
            field=models.ManyToManyField(related_name='user_profile', to='musicBlogger.songs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
