# Generated by Django 4.1.7 on 2023-03-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlogger', '0002_rename_name_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
