# Generated by Django 4.1.7 on 2023-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlogger', '0003_alter_blogs_text_alter_blogs_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
