# Generated by Django 4.1.7 on 2023-03-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlogger', '0003_alter_blogs_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='name',
            new_name='title',
        ),
    ]
