# Generated by Django 4.1.7 on 2023-03-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicBlogger", "0003_alter_blogs_text_alter_blogs_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="text",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
