# Generated by Django 4.1.7 on 2023-03-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlogger', '0004_alter_songs_text'),
        ('musicBlogger', '0004_blogs_slug_alter_blogs_title'),
    ]

    operations = [
    ]
