# Generated by Django 4.1.7 on 2023-03-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicBlogger', '0004_rename_name_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
